spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transactional?serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: com.bunny.spring.framework.entity
